project:
  type: book # website
  output-dir: "_build"
  preview:
    port: 4567
    browser: true


  render:
    # be able to link to these other hidden documents not included in the sidebar contents
    # (this doesn't work though???)
    # https://quarto.org/docs/projects/quarto-projects.html#render-targets
    # https://github.com/quarto-dev/quarto-cli/discussions/7312#discussioncomment-7345228
    - prereqs/local-dev-setup/terminal-config.qmd
    - prereqs/local-dev-setup/vs-code-config.qmd
    - exercises/run-the-app/troubleshooting.qmd
    - notes/clis/brew.qmd


# https://quarto.org/docs/books/
# https://quarto.org/docs/reference/projects/books.html
book:
  title: "Local Development Tools for Python Programming"
  author: "Michael Rossetti"
  date: "last-modified" # "7/24/2024"
  date-format: "iso"
  #doi: "...."
  #isbn: "..."
  #issn: "..."
  #edition: "v2"

#website:

  site-url: https://s2t2.github.io/python-dev-tools-workshop-2024/
  repo-url: https://github.com/s2t2/python-dev-tools-workshop-2024
  repo-branch: main
  repo-subdir: docs
  repo-actions: [edit, issue, source]
  #downloads: [pdf, epub, docx]

  # https://quarto.org/docs/websites/website-tools.html#google-analytics
  #google-analytics: "G-..."

  #sharing: [twitter, facebook]
  # https://quarto.org/docs/websites/website-tools.html#open-graph
  open-graph: true

  # https://quarto.org/docs/reference/projects/books.html#search
  search: true
    #location: sidebar # navbar, sidebar
    #type: textbox # overlay, textbox

  #cover-image: images/cover.png
  #favicon: images/favicon.ico

  # https://quarto.org/docs/websites/website-navigation.html#side-navigation
  #sidebar:
  #  logo: images/ospo-logo.png

  #sidebar:
  #  contents:
  #    - index.qmd
  #
  #    - section:
  #      href: prereqs/local-dev-setup/index.qmd
  #      title: "Prerequisites"
  #      contents:
  #        - prereqs/local-dev-setup/github.qmd
  #        - prereqs/local-dev-setup/vs-code-text-editor.qmd
  #        - prereqs/local-dev-setup/terminal.qmd
  #        - prereqs/local-dev-setup/anaconda.qmd
  #        - prereqs/local-dev-setup/git-client.qmd


  chapters:
    - index.qmd

    - "-------------"

    - part: "Setup Guide (Prereqs)"
      href: prereqs/local-dev-setup/index.qmd
      chapters:
        - prereqs/local-dev-setup/github.qmd
        - prereqs/local-dev-setup/vs-code-text-editor.qmd
        - prereqs/local-dev-setup/terminal.qmd
        - prereqs/local-dev-setup/anaconda.qmd
        - prereqs/local-dev-setup/git-client.qmd



    - "-------------"

    - part: "Workshop Exercises"
      chapters:
        - href: exercises/command-line-computing/index.qmd
          text: Command-line Computing
        - href: exercises/hello-python/index.qmd
          text: Hello Python
        - href: exercises/run-the-app/index.qmd
          text: Run the App (Tic Tac Toe)


    - "-------------"


  #appendices:


  # shows up at bottom of page
  #body-footer: "&copy; Copyright 2024, Your Name Here"

  #page-footer:
  #  center: |
  #    <p>&copy; Copyright 2024, GWU Open Source Program Office (OSPO)</p>


#bibliography: references.bib

format:
  html:
    # https://quarto.org/docs/output-formats/html-themes.html
    theme:
      light: default #flatly
      dark: darkly
    css: styles.css
    number-sections: false
    from: markdown+emoji # enable emojis


  #pdf:
  #  documentclass: scrreprt
